# valorpc private host entries

Host pve-main
  HostName 10.10.23.110
  User root
  IdentityFile ~/.ssh/ssh-key-2021-10-20.key
  IdentitiesOnly yes

Host oracle-20260203
  HostName 138.2.23.144
  User ubuntu
  IdentityFile ~/.ssh/instance-20260203-1332-ssh-key-2026-02-03.key
  IdentitiesOnly yes
