# macmini private host entries
IgnoreUnknown UseKeychain

Host github-work
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519_work
  IdentitiesOnly yes
  UseKeychain yes

Host corp-proxy
  HostName 10.10.23.155
  User root
  IdentityFile ~/.ssh/google_compute_engine
  IdentitiesOnly yes
